-- MERX Public Demo Sandbox
-- Run once in Supabase SQL Editor. Production tables are not altered.

create extension if not exists pgcrypto;

create table if not exists public.demo_workspaces (
  id uuid primary key,
  label text not null default 'MERX Public Demo',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists public.demo_store_settings (
  workspace_id uuid primary key references public.demo_workspaces(id) on delete cascade,
  store_name text not null default 'MERX Demo Store',
  primary_color text not null default '#1B2A4A',
  accent_color text not null default '#F3EFE7',
  hero_title text not null default 'Demo Admin MERX',
  hero_description text not null default '',
  hero_image_url text not null default '/images/header-homepage.png',
  business jsonb not null default '{}'::jsonb,
  commerce_settings jsonb not null default '{"shippingFee":15000,"taxRate":11}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.demo_products (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.demo_workspaces(id) on delete cascade,
  title text not null,
  slug text not null,
  src_url text not null,
  gallery jsonb not null default '[]'::jsonb,
  price bigint not null default 0,
  tax jsonb not null default '{"mode":"auto","rate":null}'::jsonb,
  discount jsonb not null default '{"amount":0,"percentage":0,"source":"manual"}'::jsonb,
  pricing jsonb not null default '{"mode":"manual","target":0}'::jsonb,
  rating numeric(3,2) not null default 0,
  review_count integer not null default 0,
  category text not null default 'Other',
  gender text not null default 'Unisex',
  color text not null default 'Default',
  sizes jsonb not null default '[]'::jsonb,
  description text not null default '',
  details jsonb not null default '{}'::jsonb,
  faqs jsonb not null default '[]'::jsonb,
  reviews jsonb not null default '[]'::jsonb,
  source_page text not null default '',
  source_id text not null default '',
  source_description text not null default '',
  stock integer not null default 0,
  cost_price bigint not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (workspace_id, slug)
);

create table if not exists public.demo_orders (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.demo_workspaces(id) on delete cascade,
  order_code text not null unique,
  customer_name text not null,
  customer_email text not null,
  phone text,
  address text,
  payment_method text not null,
  status text not null default 'paid',
  subtotal bigint not null default 0,
  tax_total bigint not null default 0,
  total bigint not null default 0,
  cost_total bigint not null default 0,
  shipping jsonb not null default '{}'::jsonb,
  delivery_status text not null default 'pending',
  delivered_at timestamptz,
  other_cost bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.demo_order_items (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.demo_workspaces(id) on delete cascade,
  order_id bigint not null references public.demo_orders(id) on delete cascade,
  product_id bigint not null,
  title text not null,
  quantity integer not null default 1,
  unit_price bigint not null default 0,
  cost_price bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.demo_wishlist_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.demo_workspaces(id) on delete cascade,
  product_id bigint not null,
  user_key text not null default 'demo',
  event_type text not null default 'save',
  created_at timestamptz not null default now()
);

create table if not exists public.demo_discount_rules (
  workspace_id uuid primary key references public.demo_workspaces(id) on delete cascade,
  name text not null default 'Stok menipis',
  enabled boolean not null default false,
  stock_threshold integer not null default 5,
  percentage integer not null default 10,
  updated_at timestamptz not null default now()
);

create table if not exists public.demo_store_wallets (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null unique references public.demo_workspaces(id) on delete cascade,
  balance bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.demo_wallet_transactions (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.demo_workspaces(id) on delete cascade,
  wallet_id bigint not null references public.demo_store_wallets(id) on delete cascade,
  direction text not null check (direction in ('credit','debit')),
  transaction_type text not null check (transaction_type in ('sale','withdrawal','refund','adjustment')),
  amount bigint not null check (amount > 0),
  reference_key text not null unique,
  reference_type text,
  reference_id text,
  method text,
  destination text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.demo_workspaces enable row level security;
alter table public.demo_store_settings enable row level security;
alter table public.demo_products enable row level security;
alter table public.demo_orders enable row level security;
alter table public.demo_order_items enable row level security;
alter table public.demo_wishlist_events enable row level security;
alter table public.demo_discount_rules enable row level security;
alter table public.demo_store_wallets enable row level security;
alter table public.demo_wallet_transactions enable row level security;

-- No anon/authenticated policies: these sandbox tables are server-only via service_role.
