import { NextResponse } from "next/server";
import { dbConfigured, supabaseRequest } from "@/lib/server/supabase";
function esc(s:string){return String(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]||c));}
export async function POST(req:Request){try{const body=await req.json();const {customer,items,total,payment,lang="id"}=body||{};if(!customer?.name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(customer?.email||"")||!Array.isArray(items)||!items.length||typeof total!=="number")return NextResponse.json({error:"Data checkout tidak valid"},{status:400});
 const orderId=`MERX-${Date.now().toString(36).toUpperCase()}`; let emailSent=false;
 if(dbConfigured){try{const ids=items.map((i:any)=>Number(i.id)).filter(Boolean);const dbProducts=ids.length?await supabaseRequest<any[]>(`products?select=id,title,cost_price,stock&id=in.(${ids.join(",")})&limit=500`):[];let costTotal=0;for(const item of items){const p=dbProducts.find(x=>Number(x.id)===Number(item.id));const qty=Math.max(1,Number(item.quantity)||1);if(p){if(Number(p.stock)<qty)return NextResponse.json({error:`Stok ${p.title} tidak mencukupi.`},{status:409});costTotal+=Number(p.cost_price||0)*qty;}}
 const orderRows=await supabaseRequest<any[]>("orders",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({order_code:orderId,customer_name:customer.name,customer_email:customer.email,phone:customer.phone||"",address:customer.address||"",payment_method:payment||"card",status:"paid",total:Math.round(total),cost_total:Math.round(costTotal)})});const dbOrderId=orderRows?.[0]?.id;
 const itemRows=items.map((i:any)=>{const p=dbProducts.find(x=>Number(x.id)===Number(i.id));const qty=Math.max(1,Number(i.quantity)||1);return{order_id:dbOrderId,product_id:Number(i.id),title:String(i.name||p?.title||`Produk ${i.id}`),quantity:qty,unit_price:Math.round(Number(i.price||0)),cost_price:Number(p?.cost_price||0)}});await supabaseRequest("order_items",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(itemRows)});
 for(const item of itemRows){const p=dbProducts.find(x=>Number(x.id)===item.product_id);if(p)await supabaseRequest(`products?id=eq.${item.product_id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({stock:Math.max(0,Number(p.stock)-item.quantity),updated_at:new Date().toISOString()})});}
 }catch(err){return NextResponse.json({error:err instanceof Error?err.message:"Gagal menyimpan pesanan ke database"},{status:500});}}
 const apiKey=process.env.RESEND_API_KEY;const from=process.env.RESEND_FROM_EMAIL;if(apiKey&&from){const id=lang==="id";const html=`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto"><h1>MERX ${id?'Bukti Pembayaran':'Payment Receipt'}</h1><p>${id?'Halo':'Hi'} ${esc(customer.name)}, ${id?'pembayaran kamu sudah dikonfirmasi.':'your payment has been confirmed.'}</p><p><b>${id?'Pesanan':'Order'}:</b> ${orderId}</p><p><b>${id?'Metode':'Method'}:</b> ${esc(payment||'card')}</p><p><b>Total:</b> Rp ${Number(total).toLocaleString('id-ID')}</p><ul>${items.map((i:any)=>`<li>${esc(i.name)} × ${Number(i.quantity)||1}</li>`).join('')}</ul></div>`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[customer.email],subject:`MERX ${id?"Bukti Pembayaran":"Receipt"} ${orderId}`,html})});emailSent=r.ok;}
 return NextResponse.json({orderId,emailSent},{status:200});}catch{return NextResponse.json({error:"Tidak dapat memproses checkout"},{status:500});}}
