"use client";
import React,{useEffect,useMemo,useState} from "react";
import { motion } from "framer-motion";
import { BarChart3, Boxes, ChevronRight, LogOut, Package, Percent, Plus, Settings, ShoppingBag, Store, TrendingUp } from "lucide-react";
import { formatIDR } from "@/lib/catalog";

type AdminProduct={id:number;title:string;slug:string;src_url?:string;srcUrl?:string;price:number;discount:{amount:number;percentage:number};category:string;gender:string;color:string;sizes:string[];description:string;stock:number;cost_price?:number;costPrice?:number;is_active?:boolean;isActive?:boolean;rating:number;reviewCount:number;gallery?:string[];details?:Record<string,string>;faqs?:any[];reviews?:any[]};
type Analytics={configured:boolean;revenue:number;cost:number;profit:number;orders:number;topCheckout:{id:number;title:string;count:number}[];topSaved:{id:number;title:string;count:number}[];lowStock:{id:number;title:string;stock:number}[]};
type Settings={store_name?:string;storeName?:string;primary_color?:string;primaryColor?:string;accent_color?:string;accentColor?:string;hero_title?:string;heroTitle?:string;hero_description?:string;heroDescription?:string;hero_image_url?:string;heroImageUrl?:string};

const input="w-full rounded-xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#1B2A4A]";
const card="rounded-2xl border border-black/10 bg-white";

export default function AdminPage(){
 const [session,setSession]=useState<any>(null); const [tab,setTab]=useState("dashboard"); const [products,setProducts]=useState<AdminProduct[]>([]); const [orders,setOrders]=useState<any[]>([]); const [analytics,setAnalytics]=useState<Analytics|null>(null); const [settings,setSettings]=useState<Settings>({}); const [discount,setDiscount]=useState<any>({enabled:false,stockThreshold:5,percentage:10}); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const [editing,setEditing]=useState<AdminProduct|null>(null);
 useEffect(()=>{fetch("/api/admin/session").then(r=>r.json()).then(setSession);},[]);
 const refresh=async()=>{const [p,o,a,s,d]=await Promise.all([fetch("/api/admin/products"),fetch("/api/admin/orders"),fetch("/api/admin/analytics"),fetch("/api/admin/settings"),fetch("/api/admin/discounts")]); if(p.ok)setProducts(await p.json()); if(o.ok)setOrders(await o.json()); if(a.ok)setAnalytics(await a.json()); if(s.ok)setSettings(await s.json()); if(d.ok)setDiscount(await d.json());};
 useEffect(()=>{if(session?.authenticated) refresh().catch(()=>{});},[session?.authenticated]);
 if(session===null)return <div className="min-h-screen grid place-items-center text-black/60">Memuat admin…</div>;
 if(!session.configured||!session.authenticated)return <AdminLogin configured={session.configured} onDone={()=>fetch("/api/admin/session").then(r=>r.json()).then(setSession)} />;
 const nav=[{id:"dashboard",label:"Ringkasan",icon:TrendingUp},{id:"products",label:"Produk & Stok",icon:Package},{id:"orders",label:"Pesanan",icon:ShoppingBag},{id:"discounts",label:"Diskon",icon:Percent},{id:"settings",label:"Toko & Tampilan",icon:Store}];
 const lowStock=products.filter(p=>Number(p.stock||0)<=5).sort((a,b)=>a.stock-b.stock).slice(0,7);
 const saveProduct=async(p:AdminProduct)=>{setSaving(true);setError("");try{const method=products.some(x=>x.id===p.id)?"PATCH":"POST";const r=await fetch("/api/admin/products",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});const data=await r.json();if(!r.ok)throw new Error(data.error||"Gagal menyimpan produk");setEditing(null);await refresh();}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan");}finally{setSaving(false)}};
 const logout=async()=>{await fetch("/api/admin/logout",{method:"POST"});location.reload();};
 return <div className="min-h-screen bg-[#f6f3ed] text-[#1B2A4A]"><div className="flex min-h-screen">
  <aside className="hidden w-72 shrink-0 border-r border-black/10 bg-white p-6 lg:flex lg:flex-col"><div className="mb-10"><div className="text-2xl font-black tracking-tight">MERX</div><div className="mt-1 text-xs uppercase tracking-[0.25em] text-black/40">Admin Studio</div></div><nav className="space-y-1">{nav.map(n=><button key={n.id} onClick={()=>setTab(n.id)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm transition ${tab===n.id?"bg-[#1B2A4A] text-white":"hover:bg-[#f5f1e9] text-black/70"}`}><n.icon size={18}/>{n.label}</button>)}</nav><div className="mt-auto border-t border-black/10 pt-5"><div className="text-xs text-black/40">Admin</div><div className="mt-1 text-sm font-medium truncate">{session.email}</div><button onClick={logout} className="mt-4 flex items-center gap-2 text-sm text-black/60 hover:text-black"><LogOut size={16}/> Keluar</button></div></aside>
  <main className="w-full min-w-0"><div className="sticky top-0 z-20 flex items-center justify-between border-b border-black/10 bg-white/90 px-4 py-4 backdrop-blur lg:px-8"><div><div className="text-sm font-medium lg:hidden">MERX Admin Studio</div><div className="hidden text-sm text-black/50 lg:block">Kontrol toko, katalog, stok, diskon, dan performa</div></div><a href="/" className="text-sm font-medium">Lihat toko <ChevronRight size={15} className="inline"/></a></div>
   <div className="px-4 py-6 lg:px-8 lg:py-8">{tab==="dashboard"&&<Dashboard analytics={analytics} products={products} lowStock={lowStock}/>} {tab==="products"&&<Products products={products} setEditing={setEditing} onAdd={()=>setEditing(blankProduct(products))}/>} {tab==="orders"&&<Orders orders={orders}/>} {tab==="discounts"&&<Discounts value={discount} setValue={setDiscount} onSave={async()=>{setSaving(true);await fetch("/api/admin/discounts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(discount)});setSaving(false);}} saving={saving}/>} {tab==="settings"&&<StoreSettings value={settings} setValue={setSettings} onSave={async()=>{setSaving(true);const payload=toSettings(settings);const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)setError((await r.json()).error||"Gagal menyimpan");setSaving(false);}} saving={saving}/>}</div>
  </main></div>{editing&&<ProductEditor product={editing} saving={saving} error={error} onClose={()=>{setEditing(null);setError("")}} onSave={saveProduct}/>} </div>
}
function AdminLogin({configured,onDone}:{configured:boolean;onDone:()=>void}){const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setError(d.error||"Gagal masuk");return}onDone()};return <main className="min-h-screen bg-[#f6f3ed] grid place-items-center px-4"><motion.form initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} onSubmit={submit} className={`${card} w-full max-w-md p-7`}><div className="text-3xl font-black text-[#1B2A4A]">MERX</div><div className="mt-1 text-sm text-black/50">Admin Studio</div>{!configured&&<div className="mt-6 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-900">Tambahkan MERX_ADMIN_EMAIL, MERX_ADMIN_PASSWORD, dan MERX_ADMIN_SECRET di Vercel.</div>}<label className="mt-6 block text-sm">Email admin<input className={`${input} mt-2`} value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label className="mt-4 block text-sm">Kata sandi<input className={`${input} mt-2`} value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label><button disabled={!configured} className="mt-6 h-12 w-full rounded-xl bg-[#1B2A4A] text-white disabled:opacity-40">Masuk ke Admin</button>{error&&<p className="mt-4 text-sm text-red-700">{error}</p>}</motion.form></main>}
function Dashboard({analytics,products,lowStock}:{analytics:Analytics|null;products:AdminProduct[];lowStock:AdminProduct[]}){const revenue=analytics?.revenue||0,cost=analytics?.cost||0,profit=analytics?.profit||0;return <div><div className="mb-7 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.24em] text-black/40">Dashboard</p><h1 className="mt-2 text-3xl font-semibold lg:text-4xl">Gambaran toko</h1><p className="mt-2 text-black/55">Pantau penjualan, margin, stok, dan produk yang paling diminati.</p></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Pendapatan" value={formatIDR(revenue)}/><Metric title="Modal" value={formatIDR(cost)}/><Metric title="Keuntungan" value={formatIDR(profit)} positive={profit>=0}/><Metric title="Pesanan" value={String(analytics?.orders||0)}/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Sering checkout">{analytics?.topCheckout?.length?<ol className="space-y-3">{analytics.topCheckout.slice(0,6).map((x,i)=><li key={x.id} className="flex items-center justify-between"><span><b className="mr-3 text-black/30">{String(i+1).padStart(2,"0")}</b>{x.title}</span><span className="text-sm font-medium">{x.count} item</span></li>)}</ol>:<Empty text="Belum ada data checkout."/>}</Panel><Panel title="Sering disimpan">{analytics?.topSaved?.length?<ol className="space-y-3">{analytics.topSaved.slice(0,6).map((x,i)=><li key={x.id} className="flex items-center justify-between"><span><b className="mr-3 text-black/30">{String(i+1).padStart(2,"0")}</b>{x.title}</span><span className="text-sm font-medium">{x.count} simpan</span></li>)}</ol>:<Empty text="Belum ada data simpan."/>}</Panel></div><Panel title="Peringatan stok" className="mt-6">{lowStock.length?<div className="grid gap-3 sm:grid-cols-2">{lowStock.map(p=><div key={p.id} className="rounded-xl bg-[#f6f3ed] p-4 flex justify-between"><span className="truncate pr-4">{p.title}</span><b className={p.stock<=0?"text-red-700":"text-[#1B2A4A]"}>{p.stock} pcs</b></div>)}</div>:<Empty text="Semua stok aman."/>}</Panel></div>}
function Products({products,setEditing,onAdd}:{products:AdminProduct[];setEditing:(p:AdminProduct)=>void;onAdd:()=>void}){const [q,setQ]=useState("");const list=useMemo(()=>products.filter(p=>p.title.toLowerCase().includes(q.toLowerCase())||p.category.toLowerCase().includes(q.toLowerCase())).slice(0,100),[products,q]);return <div><Header title="Produk & Stok" text={`${products.length} produk di database`} action={<button onClick={onAdd} className="inline-flex items-center gap-2 rounded-xl bg-[#1B2A4A] px-4 py-3 text-sm text-white"><Plus size={17}/> Produk baru</button>}/><input className={`${input} mb-5 max-w-md`} placeholder="Cari produk…" value={q} onChange={e=>setQ(e.target.value)}/><div className={`${card} overflow-hidden`}><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#faf8f4] text-left text-black/45"><tr><th className="p-4">Produk</th><th>Harga</th><th>Modal</th><th>Diskon</th><th>Stok</th><th></th></tr></thead><tbody>{list.map(p=>{const img=p.src_url||p.srcUrl||"/images/header-homepage.png";return <tr key={p.id} className="border-t border-black/5"><td className="p-4 min-w-[280px]"><div className="flex items-center gap-3"><img src={img} onError={e=>e.currentTarget.src="/images/header-homepage.png"} className="h-14 w-14 rounded-lg object-cover bg-[#f3efe7]" alt=""/><div><div className="font-medium">{p.title}</div><div className="text-xs text-black/45">{p.category} · {p.color}</div></div></div></td><td>{formatIDR(p.price)}</td><td>{formatIDR(p.cost_price??p.costPrice??0)}</td><td>{p.discount?.percentage?`${p.discount.percentage}%`:"—"}</td><td><span className={p.stock<=5?"font-semibold text-red-700":"font-medium"}>{p.stock}</span></td><td className="pr-4 text-right"><button onClick={()=>setEditing(p)} className="rounded-lg border border-black/10 px-3 py-2">Edit</button></td></tr>})}</tbody></table></div></div></div>}
function Orders({orders}:{orders:any[]}){return <div><Header title="Pesanan" text="Pesanan terbaru dan status pembayarannya"/>{orders.length?<div className={`${card} overflow-hidden`}><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#faf8f4] text-left text-black/45"><tr><th className="p-4">Order</th><th>Customer</th><th>Pembayaran</th><th>Total</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t border-black/5"><td className="p-4 font-medium">{o.order_code}</td><td>{o.customer_name}<div className="text-xs text-black/40">{o.customer_email}</div></td><td>{o.payment_method}</td><td>{formatIDR(o.total)}</td><td>{o.status}</td><td>{new Date(o.created_at).toLocaleDateString("id-ID")}</td></tr>)}</tbody></table></div></div>:<Empty text="Belum ada pesanan tersimpan di database."/>}</div>}
function Discounts({value,setValue,onSave,saving}:{value:any;setValue:(x:any)=>void;onSave:()=>void;saving:boolean}){return <div><Header title="Diskon" text="Atur diskon manual dan otomatis berdasarkan stok"/><div className="grid gap-6 lg:grid-cols-2"><section className={`${card} p-6`}><h2 className="text-lg font-semibold">Diskon otomatis stok menipis</h2><p className="mt-1 text-sm text-black/50">Saat stok berada di bawah ambang, admin dapat memakai aturan ini sebagai panduan diskon.</p><label className="mt-6 flex items-center gap-3"><input type="checkbox" checked={!!value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/> Aktif</label><div className="mt-5 grid grid-cols-2 gap-4"><label className="text-sm">Stok ≤<input className={`${input} mt-2`} type="number" min="0" value={value.stockThreshold} onChange={e=>setValue({...value,stockThreshold:Number(e.target.value)})}/></label><label className="text-sm">Diskon %<input className={`${input} mt-2`} type="number" min="0" max="90" value={value.percentage} onChange={e=>setValue({...value,percentage:Number(e.target.value)})}/></label></div><button onClick={onSave} className="mt-6 rounded-xl bg-[#1B2A4A] px-5 py-3 text-sm text-white">{saving?"Menyimpan…":"Simpan aturan"}</button></section><section className={`${card} p-6`}><h2 className="text-lg font-semibold">Diskon per produk</h2><p className="mt-2 text-sm text-black/50">Gunakan tab Produk & Stok untuk mengubah persentase diskon setiap item. Harga jual dihitung otomatis oleh katalog.</p></section></div></div>}
function StoreSettings({value,setValue,onSave,saving}:{value:Settings;setValue:(v:Settings)=>void;onSave:()=>void;saving:boolean}){const v=(k:keyof Settings,alt="")=>(value[k]??alt);return <div><Header title="Toko & Tampilan" text="Ubah identitas, warna, hero, dan copy toko"/><div className="grid gap-6 lg:grid-cols-[1fr_340px]"><section className={`${card} p-6 space-y-5`}><label className="block text-sm">Nama toko<input className={`${input} mt-2`} value={v("storeName",v("store_name","MERX"))} onChange={e=>setValue({...value,storeName:e.target.value})}/></label><div className="grid grid-cols-2 gap-4"><label className="text-sm">Warna utama<input className="mt-2 h-12 w-full rounded-xl border border-black/10 bg-white p-1" type="color" value={v("primaryColor",v("primary_color","#1B2A4A"))} onChange={e=>setValue({...value,primaryColor:e.target.value})}/></label><label className="text-sm">Warna latar<input className="mt-2 h-12 w-full rounded-xl border border-black/10 bg-white p-1" type="color" value={v("accentColor",v("accent_color","#F3EFE7"))} onChange={e=>setValue({...value,accentColor:e.target.value})}/></label></div><label className="block text-sm">Judul hero<textarea className={`${input} mt-2 min-h-24`} value={v("heroTitle",v("hero_title",""))} onChange={e=>setValue({...value,heroTitle:e.target.value})}/></label><label className="block text-sm">Deskripsi hero<textarea className={`${input} mt-2 min-h-28`} value={v("heroDescription",v("hero_description",""))} onChange={e=>setValue({...value,heroDescription:e.target.value})}/></label><label className="block text-sm">URL gambar hero<input className={`${input} mt-2`} value={v("heroImageUrl",v("hero_image_url",""))} onChange={e=>setValue({...value,heroImageUrl:e.target.value})}/></label><button onClick={onSave} className="rounded-xl bg-[#1B2A4A] px-5 py-3 text-sm text-white">{saving?"Menyimpan…":"Simpan perubahan"}</button></section><section className={`${card} p-6`}><div className="text-xs uppercase tracking-[.2em] text-black/40">Pratinjau</div><div className="mt-5 rounded-2xl p-6" style={{background:v("accentColor",v("accent_color","#F3EFE7"))}}><div className="text-xl font-black" style={{color:v("primaryColor",v("primary_color","#1B2A4A"))}}>{v("storeName",v("store_name","MERX"))}</div><div className="mt-8 text-3xl font-semibold" style={{color:v("primaryColor",v("primary_color","#1B2A4A"))}}>{v("heroTitle")}</div><p className="mt-3 text-sm text-black/55">{v("heroDescription")}</p></div></section></div></div>}
function ProductEditor({product,saving,error,onClose,onSave}:{product:AdminProduct;saving:boolean;error:string;onClose:()=>void;onSave:(p:AdminProduct)=>void}){const [p,setP]=useState(product);return <div className="fixed inset-0 z-50 bg-black/45 p-3 sm:p-6"><div className="mx-auto flex h-full max-w-5xl flex-col overflow-hidden rounded-3xl bg-white"><div className="flex items-center justify-between border-b border-black/10 px-5 py-4"><div><div className="font-semibold">{product.title?"Edit produk":"Tambah produk"}</div><div className="text-xs text-black/45">Perubahan disimpan ke database</div></div><button onClick={onClose} className="text-black/50">Tutup</button></div><div className="flex-1 overflow-y-auto p-5"><div className="grid gap-5 md:grid-cols-2"><Field label="Nama" value={p.title} onChange={v=>setP({...p,title:v})}/><Field label="Slug" value={p.slug} onChange={v=>setP({...p,slug:v})}/><Field label="Harga" value={String(p.price)} type="number" onChange={v=>setP({...p,price:Number(v)})}/><Field label="Modal" value={String(p.cost_price??p.costPrice??0)} type="number" onChange={v=>setP({...p,cost_price:Number(v)})}/><Field label="Stok" value={String(p.stock??0)} type="number" onChange={v=>setP({...p,stock:Number(v)})}/><Field label="Diskon %" value={String(p.discount?.percentage??0)} type="number" onChange={v=>setP({...p,discount:{amount:0,percentage:Number(v)}})}/><Field label="Kategori" value={p.category} onChange={v=>setP({...p,category:v})}/><Field label="Warna" value={p.color} onChange={v=>setP({...p,color:v})}/><Field label="URL gambar" value={p.src_url||p.srcUrl||""} onChange={v=>setP({...p,srcUrl:v,src_url:v})}/><Field label="Gender" value={p.gender} onChange={v=>setP({...p,gender:v})}/></div><label className="mt-5 block text-sm">Deskripsi<textarea className={`${input} mt-2 min-h-36`} value={p.description||""} onChange={e=>setP({...p,description:e.target.value})}/></label><label className="mt-5 block text-sm">Ukuran <input className={`${input} mt-2`} value={(p.sizes||[]).join(", ")} onChange={e=>setP({...p,sizes:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label>{error&&<p className="mt-4 text-sm text-red-700">{error}</p>}</div><div className="border-t border-black/10 p-5 flex justify-end gap-3"><button onClick={onClose} className="rounded-xl border border-black/10 px-5 py-3">Batal</button><button onClick={()=>onSave({...p,id:p.id||Date.now()})} className="rounded-xl bg-[#1B2A4A] px-5 py-3 text-white">{saving?"Menyimpan…":"Simpan produk"}</button></div></div></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-sm">{label}<input className={`${input} mt-2`} type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Metric({title,value,positive}:{title:string;value:string;positive?:boolean}){return <div className={`${card} p-5`}><div className="text-xs uppercase tracking-[.18em] text-black/40">{title}</div><div className={`mt-3 text-2xl font-semibold ${positive===false?"text-red-700":""}`}>{value}</div></div>}
function Panel({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <section className={`${card} p-6 ${className}`}><h2 className="text-lg font-semibold mb-5">{title}</h2>{children}</section>}
function Empty({text}:{text:string}){return <div className="rounded-xl bg-[#f6f3ed] p-5 text-sm text-black/50">{text}</div>}
function Header({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.24em] text-black/40">MERX ADMIN</p><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-black/55">{text}</p></div>{action}</div>}
function blankProduct(products:AdminProduct[]):AdminProduct{return {id:Math.max(0,...products.map(p=>p.id))+1,title:"",slug:"",srcUrl:"/images/header-homepage.png",src_url:"/images/header-homepage.png",price:0,discount:{amount:0,percentage:0},rating:0,reviewCount:0,category:"T-Shirts",gender:"Unisex",color:"White",sizes:["S","M","L"],description:"",stock:0,cost_price:0,isActive:true};}
function toSettings(v:Settings){return {storeName:v.storeName||v.store_name,primaryColor:v.primaryColor||v.primary_color,accentColor:v.accentColor||v.accent_color,heroTitle:v.heroTitle||v.hero_title,heroDescription:v.heroDescription||v.hero_description,heroImageUrl:v.heroImageUrl||v.hero_image_url};}
